:PROPERTIES:
:ID:       76ad038a-1550-4e32-b7df-e5fe3edb20a3
:ROAM_REFS: cite:chenPix2seqLanguageModeling2022
:END:
#+title: pix2seq

Pix2seq is a task-agnostic (generic) framework for [[id:667882a1-fc54-4f84-8eac-f1f009da5aba][object detection]]. It cast
object detection as a language modeling task, conditioned on the observed pixel
input. Pix2seq proposed a general intelligence system, in contrast to most
existing methods that are specialized and difficult to integrate to larger
system. The model provides a language interface by producing a sequence of
discrete tokens that correspond to object descriptions. The objective function
defined in the model is simple the maximum likelihood of tokens given the pixel
inputs and the preceding tokens. The model can be configured to task-specific
prior knowledge with a sequence augmentation technique. Based on the reported
experiments, Pix2seq has a comparable result to SOTA object detection models
such as [[id:e840c4b3-e08a-40f9-85bd-b31e56e30473][Faster R-CNN]].
